name: Build and Push to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to ACR
      uses: docker/login-action@v2
      with:
        registry: projectsentimentacr.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build -t projectsentimentacr.azurecr.io/sentiment-app:latest .
        docker push projectsentimentacr.azurecr.io/sentiment-app:latest
